import { Catalog } from "@/types";

export const catalogs: Catalog[] = [
  {
    id: "catalog1",
    name: "uMANILA/eth",
    nfts: [
      {
        id: "nft1",
        name: "NFT_NAME",
        image: "/images/image_4.png",
        collectionName: "CloneX",
        price: 29.76,
        withExclusiveLicense: false,
        ownerName: "",
        ownerUserId: "",
        ownerLastActive: new Date(),
        traits: [],
        contractAddress: "",
        tokenId: "",
        tokenStandard: "",
        blockchain: "",
        contractProposals: 0,
        activeContracts: 0,
        endedContracts: 0,
        catalogCount: 0,
        views: 0,
        amountEarned: 0,
        averageContractLength: "",
        private: false,
      },
      {
        id: "nft2",
        name: "NFT_NAME",
        image: "/images/image_4.png",
        collectionName: "CloneX",
        price: 29.76,
        withExclusiveLicense: true,
        ownerName: "",
        ownerUserId: "",
        ownerLastActive: new Date(),
        traits: [],
        contractAddress: "",
        tokenId: "",
        tokenStandard: "",
        blockchain: "",
        contractProposals: 0,
        activeContracts: 0,
        endedContracts: 0,
        catalogCount: 0,
        views: 0,
        amountEarned: 0,
        averageContractLength: "",
        private: false,
      },
      {
        id: "nft3",
        name: "NFT_NAME",
        image: "/images/image_4.png",
        collectionName: "CloneX",
        price: 29.76,
        withExclusiveLicense: true,
        ownerName: "",
        ownerUserId: "",
        ownerLastActive: new Date(),
        traits: [],
        contractAddress: "",
        tokenId: "",
        tokenStandard: "",
        blockchain: "",
        contractProposals: 0,
        activeContracts: 0,
        endedContracts: 0,
        catalogCount: 0,
        views: 0,
        amountEarned: 0,
        averageContractLength: "",
        private: false,
      },
      {
        id: "nft4",
        name: "NFT_NAME",
        image: "/images/image_4.png",
        collectionName: "CloneX",
        price: 29.76,
        withExclusiveLicense: false,
        ownerName: "",
        ownerUserId: "",
        ownerLastActive: new Date(),
        traits: [],
        contractAddress: "",
        tokenId: "",
        tokenStandard: "",
        blockchain: "",
        contractProposals: 0,
        activeContracts: 0,
        endedContracts: 0,
        catalogCount: 0,
        views: 0,
        amountEarned: 0,
        averageContractLength: "",
        private: false,
      },
      {
        id: "nft5",
        name: "NFT_NAME",
        image: "/images/image_4.png",
        collectionName: "CloneX",
        price: 29.76,
        withExclusiveLicense: true,
        ownerName: "",
        ownerUserId: "",
        ownerLastActive: new Date(),
        traits: [],
        contractAddress: "",
        tokenId: "",
        tokenStandard: "",
        blockchain: "",
        contractProposals: 0,
        activeContracts: 0,
        endedContracts: 0,
        catalogCount: 0,
        views: 0,
        amountEarned: 0,
        averageContractLength: "",
        private: false,
      },
      {
        id: "nft6",
        name: "NFT_NAME",
        image: "/images/image_4.png",
        collectionName: "CloneX",
        price: 29.76,
        withExclusiveLicense: false,
        ownerName: "",
        ownerUserId: "",
        ownerLastActive: new Date(),
        traits: [],
        contractAddress: "",
        tokenId: "",
        tokenStandard: "",
        blockchain: "",
        contractProposals: 0,
        activeContracts: 0,
        endedContracts: 0,
        catalogCount: 0,
        views: 0,
        amountEarned: 0,
        averageContractLength: "",
        private: false,
      },
    ],
    creatorName: "",
    creatorUserId: "",
    createdAt: new Date(),
    coverImage: "",
    coverColor: "",
    allowExclusiveLicense: false,
  },
  {
    id: "catalog2",
    name: "CloneX Col.",
    nfts: [
      {
        id: "nft7",
        name: "NFT_NAME",
        image: "/images/image_4.png",
        collectionName: "CloneX",
        price: 29.76,
        withExclusiveLicense: false,
        ownerName: "",
        ownerUserId: "",
        ownerLastActive: new Date(),
        traits: [],
        contractAddress: "",
        tokenId: "",
        tokenStandard: "",
        blockchain: "",
        contractProposals: 0,
        activeContracts: 0,
        endedContracts: 0,
        catalogCount: 0,
        views: 0,
        amountEarned: 0,
        averageContractLength: "",
        private: false,
      },
    ],
    creatorName: "",
    creatorUserId: "",
    createdAt: new Date(),
    coverImage: "",
    coverColor: "",
    allowExclusiveLicense: false,
  },
  {
    id: "catalog3",
    name: "Test",
    nfts: [],
    creatorName: "",
    creatorUserId: "",
    createdAt: new Date(),
    coverImage: "",
    coverColor: "",
    allowExclusiveLicense: false,
  },
];
