import { Catalog, CatalogMarketData, CatalogTrendingData, NFT, Trait, User } from "./types";

export const user : User & { password: string; } = {
  id: "1",
  email: "user@email.com",
  password: "password",
  username: "mrknuckles",
  name: "Domohariga Tomistarobato",
  pfp: "/images/image_1.png",
  walletAddress: "1Lbcfr7sAHTD9CgdQo3HTMTkV8LK4ZnX71",
  joinedAt: new Date(),
  responseTime: 77,
  responseRate: "Within the hour",
  website: "",
  twitter: "x.com/markiplier",
  instagram: "",
  discord: "",
  opensea: "",
  looksRare: "",
  catalogCount: 12,
  contractCount: 3,
};

export const catalogs: Catalog[] = [
  {
    id: "1",
    name: "Catalog 1",
    createdAt: new Date("2023-01-01"),
    coverImage: "/images/image_2.png",
    coverColor: "#FF5733",
    allowExclusiveLicense: true,
    creatorName: "Creator 1",
    creatorUserId: "creator1"
  },
  {
    id: "2",
    name: "Catalog 2",
    createdAt: new Date("2023-01-02"),
    coverImage: "/images/image_2.png",
    coverColor: "#33FF57",
    allowExclusiveLicense: false,
    creatorName: "Creator 2",
    creatorUserId: "creator2"
  },
  {
    id: "3",
    name: "Catalog 3",
    createdAt: new Date("2023-01-03"),
    coverImage: "/images/image_2.png",
    coverColor: "#5733FF",
    allowExclusiveLicense: true,
    creatorName: "Creator 3",
    creatorUserId: "creator3"
  },
  {
    id: "4",
    name: "Catalog 4",
    createdAt: new Date("2023-01-04"),
    coverImage: "/images/image_2.png",
    coverColor: "#FF33A1",
    allowExclusiveLicense: false,
    creatorName: "Creator 4",
    creatorUserId: "creator4"
  },
  {
    id: "5",
    name: "Catalog 5",
    createdAt: new Date("2023-01-05"),
    coverImage: "/images/image_2.png",
    coverColor: "#33A1FF",
    allowExclusiveLicense: true,
    creatorName: "Creator 5",
    creatorUserId: "creator5"
  },
  {
    id: "6",
    name: "Catalog 6",
    createdAt: new Date("2023-01-06"),
    coverImage: "/images/image_2.png",
    coverColor: "#A1FF33",
    allowExclusiveLicense: false,
    creatorName: "Creator 6",
    creatorUserId: "creator6"
  },
  {
    id: "7",
    name: "Catalog 7",
    createdAt: new Date("2023-01-07"),
    coverImage: "/images/image_2.png",
    coverColor: "#FF5733",
    allowExclusiveLicense: true,
    creatorName: "Creator 7",
    creatorUserId: "creator7"
  },
  {
    id: "8",
    name: "Catalog 8",
    createdAt: new Date("2023-01-08"),
    coverImage: "/images/image_2.png",
    coverColor: "#33FF57",
    allowExclusiveLicense: false,
    creatorName: "Creator 8",
    creatorUserId: "creator8"
  },
  {
    id: "9",
    name: "Catalog 9",
    createdAt: new Date("2023-01-09"),
    coverImage: "/images/image_2.png",
    coverColor: "#5733FF",
    allowExclusiveLicense: true,
    creatorName: "Creator 9",
    creatorUserId: "creator9"
  },
  {
    id: "10",
    name: "Catalog 10",
    createdAt: new Date("2023-01-10"),
    coverImage: "/images/image_2.png",
    coverColor: "#FF33A1",
    allowExclusiveLicense: false,
    creatorName: "Creator 10",
    creatorUserId: "creator10"
  },
  {
    id: "11",
    name: "Catalog 11",
    createdAt: new Date("2023-01-11"),
    coverImage: "/images/image_2.png",
    coverColor: "#33A1FF",
    allowExclusiveLicense: true,
    creatorName: "Creator 11",
    creatorUserId: "creator11"
  },
  {
    id: "12",
    name: "Catalog 12",
    createdAt: new Date("2023-01-12"),
    coverImage: "/images/image_2.png",
    coverColor: "#A1FF33",
    allowExclusiveLicense: false,
    creatorName: "Creator 12",
    creatorUserId: "creator12"
  },
  {
    id: "13",
    name: "Catalog 13",
    createdAt: new Date("2023-01-13"),
    coverImage: "/images/image_2.png",
    coverColor: "#FF5733",
    allowExclusiveLicense: true,
    creatorName: "Creator 13",
    creatorUserId: "creator13"
  },
  {
    id: "14",
    name: "Catalog 14",
    createdAt: new Date("2023-01-14"),
    coverImage: "/images/image_2.png",
    coverColor: "#33FF57",
    allowExclusiveLicense: false,
    creatorName: "Creator 14",
    creatorUserId: "creator14"
  },
  {
    id: "15",
    name: "Catalog 15",
    createdAt: new Date("2023-01-15"),
    coverImage: "/images/image_2.png",
    coverColor: "#5733FF",
    allowExclusiveLicense: true,
    creatorName: "Creator 15",
    creatorUserId: "creator15"
  },
  {
    id: "16",
    name: "Catalog 16",
    createdAt: new Date("2023-01-16"),
    coverImage: "/images/image_2.png",
    coverColor: "#FF33A1",
    allowExclusiveLicense: false,
    creatorName: "Creator 16",
    creatorUserId: "creator16"
  },
  {
    id: "17",
    name: "Catalog 17",
    createdAt: new Date("2023-01-17"),
    coverImage: "/images/image_2.png",
    coverColor: "#33A1FF",
    allowExclusiveLicense: true,
    creatorName: "Creator 17",
    creatorUserId: "creator17"
  },
  {
    id: "18",
    name: "Catalog 18",
    createdAt: new Date("2023-01-18"),
    coverImage: "/images/image_2.png",
    coverColor: "#A1FF33",
    allowExclusiveLicense: false,
    creatorName: "Creator 18",
    creatorUserId: "creator18"
  },
  {
    id: "19",
    name: "Catalog 19",
    createdAt: new Date("2023-01-19"),
    coverImage: "/images/image_2.png",
    coverColor: "#FF5733",
    allowExclusiveLicense: true,
    creatorName: "Creator 19",
    creatorUserId: "creator19"
  },
  {
    id: "20",
    name: "Catalog 20",
    createdAt: new Date("2023-01-20"),
    coverImage: "/images/image_2.png",
    coverColor: "#33FF57",
    allowExclusiveLicense: false,
    creatorName: "Creator 20",
    creatorUserId: "creator20"
  },
  {
    id: "21",
    name: "Catalog 21",
    createdAt: new Date("2023-01-21"),
    coverImage: "/images/image_2.png",
    coverColor: "#5733FF",
    allowExclusiveLicense: true,
    creatorName: "Creator 21",
    creatorUserId: "creator21"
  },
  {
    id: "22",
    name: "Catalog 22",
    createdAt: new Date("2023-01-22"),
    coverImage: "/images/image_2.png",
    coverColor: "#FF33A1",
    allowExclusiveLicense: false,
    creatorName: "Creator 22",
    creatorUserId: "creator22"
  },
  {
    id: "23",
    name: "Catalog 23",
    createdAt: new Date("2023-01-23"),
    coverImage: "/images/image_2.png",
    coverColor: "#33A1FF",
    allowExclusiveLicense: true,
    creatorName: "Creator 23",
    creatorUserId: "creator23"
  },
  {
    id: "24",
    name: "Catalog 24",
    createdAt: new Date("2023-01-24"),
    coverImage: "/images/image_2.png",
    coverColor: "#A1FF33",
    allowExclusiveLicense: false,
    creatorName: "Creator 24",
    creatorUserId: "creator24"
  },
  {
    id: "25",
    name: "Catalog 25",
    createdAt: new Date("2023-01-25"),
    coverImage: "/images/image_2.png",
    coverColor: "#FF5733",
    allowExclusiveLicense: true,
    creatorName: "Creator 25",
    creatorUserId: "creator25"
  },
  {
    id: "26",
    name: "Catalog 26",
    createdAt: new Date("2023-01-26"),
    coverImage: "/images/image_2.png",
    coverColor: "#33FF57",
    allowExclusiveLicense: false,
    creatorName: "Creator 26",
    creatorUserId: "creator26"
  },
  {
    id: "27",
    name: "Catalog 27",
    createdAt: new Date("2023-01-27"),
    coverImage: "/images/image_2.png",
    coverColor: "#5733FF",
    allowExclusiveLicense: true,
    creatorName: "Creator 27",
    creatorUserId: "creator27"
  },
  {
    id: "28",
    name: "Catalog 28",
    createdAt: new Date("2023-01-28"),
    coverImage: "/images/image_2.png",
    coverColor: "#FF33A1",
    allowExclusiveLicense: false,
    creatorName: "Creator 28",
    creatorUserId: "creator28"
  },
  {
    id: "29",
    name: "Catalog 29",
    createdAt: new Date("2023-01-29"),
    coverImage: "/images/image_2.png",
    coverColor: "#33A1FF",
    allowExclusiveLicense: true,
    creatorName: "Creator 29",
    creatorUserId: "creator29"
  },
  {
    id: "30",
    name: "Catalog 30",
    createdAt: new Date("2023-01-30"),
    coverImage: "/images/image_2.png",
    coverColor: "#A1FF33",
    allowExclusiveLicense: false,
    creatorName: "Creator 30",
    creatorUserId: "creator30"
  }
];

export const trendingCatalogs: CatalogTrendingData[] = [
  {
    id: "item1",
    rank: 1,
    price: 10.5,
    volume: 2000,
    volumeChange: 0.2,
    catalog: catalogs[0],
  },
  {
    id: "item2",
    rank: 2,
    price: 9.8,
    volume: 1800,
    volumeChange: -0.1,
    catalog: catalogs[1],
  },
  {
    id: "item3",
    rank: 3,
    price: 11.2,
    volume: 2200,
    volumeChange: 0.3,
    catalog: catalogs[2],
  },
  {
    id: "item4",
    rank: 4,
    price: 9.5,
    volume: 1900,
    volumeChange: -0.2,
    catalog: catalogs[3],
  },
  {
    id: "item5",
    rank: 5,
    price: 12.1,
    volume: 2400,
    volumeChange: 0.1,
    catalog: catalogs[4],
  },
  {
    id: "item6",
    rank: 6,
    price: 8.9,
    volume: 1700,
    volumeChange: -0.3,
    catalog: catalogs[5],
  },
  {
    id: "item7",
    rank: 7,
    price: 11.5,
    volume: 2100,
    volumeChange: 0.4,
    catalog: catalogs[6],
  },
  {
    id: "item8",
    rank: 8,
    price: 9.3,
    volume: 1850,
    volumeChange: -0.15,
    catalog: catalogs[7],
  },
  {
    id: "item9",
    rank: 9,
    price: 10.8,
    volume: 2300,
    volumeChange: 0.25,
    catalog: catalogs[8],
  },
  {
    id: "item10",
    rank: 10,
    price: 9.7,
    volume: 1950,
    volumeChange: -0.05,
    catalog: catalogs[9],
  }
];

export const marketCatalogs: CatalogMarketData[] = [
  {
    id: "item1",
    price: 10.5,
    priceChange: 0.2,
    catalog: catalogs[0],
  },
  {
    id: "item2",
    price: 9.8,
    priceChange: -0.1,
    catalog: catalogs[1],
  },
  {
    id: "item3",
    price: 11.2,
    priceChange: 0.3,
    catalog: catalogs[2],
  },
  {
    id: "item4",
    price: 9.5,
    priceChange: -0.2,
    catalog: catalogs[3],
  },
  {
    id: "item5",
    price: 12.1,
    priceChange: 0.1,
    catalog: catalogs[4],
  },
  {
    id: "item6",
    price: 8.9,
    priceChange: -0.3,
    catalog: catalogs[5],
  },
  {
    id: "item7",
    price: 11.5,
    priceChange: 0.4,
    catalog: catalogs[6],
  },
  {
    id: "item8",
    price: 9.3,
    priceChange: -0.15,
    catalog: catalogs[7],
  },
  {
    id: "item9",
    price: 10.8,
    priceChange: 0.25,
    catalog: catalogs[8],
  },
  {
    id: "item10",
    price: 9.7,
    priceChange: -0.05,
    catalog: catalogs[9],
  }
];

const traits: Trait[] = [
  { traitType: "Background", value: "Gradient 2" },
  { traitType: "Head", value: "Purple" },
  { traitType: "Hair", value: "Brown Bushcut" },
  { traitType: "Face", value: "Straw" },
  { traitType: "Body", value: "Gradient 2" },
];

export const nfts: NFT[] = [
  {
    id: "item1",
    name: "Artwork 1",
    collectionName: "Collection A",
    withExclusiveLicense: true,
    ownerName: "Owner A",
    ownerUserId: "user1",
    ownerLastActive: new Date("2023-01-01"),
    contractAddress: "0xABC123",
    tokenId: "token1",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 5,
    activeContracts: 3,
    endedContracts: 2,
    views: 1000,
    amountEarned: 500,
    averageContractLength: "2 weeks",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item2",
    name: "Artwork 2",
    collectionName: "Collection B",
    withExclusiveLicense: false,
    ownerName: "Owner B",
    ownerUserId: "user2",
    ownerLastActive: new Date("2023-01-02"),
    contractAddress: "0xDEF456",
    tokenId: "token2",
    tokenStandard: "ERC-1155",
    blockchain: "Polygon",
    contractProposals: 3,
    activeContracts: 2,
    endedContracts: 1,
    views: 800,
    amountEarned: 300,
    averageContractLength: "1 month",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item3",
    name: "Artwork 3",
    collectionName: "Collection C",
    withExclusiveLicense: true,
    ownerName: "Owner C",
    ownerUserId: "user3",
    ownerLastActive: new Date("2023-01-03"),
    contractAddress: "0xGHI789",
    tokenId: "token3",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 7,
    activeContracts: 4,
    endedContracts: 3,
    views: 1200,
    amountEarned: 700,
    averageContractLength: "3 weeks",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item4",
    name: "Artwork 4",
    collectionName: "Collection A",
    withExclusiveLicense: false,
    ownerName: "Owner A",
    ownerUserId: "user1",
    ownerLastActive: new Date("2023-01-04"),
    contractAddress: "0xJKL012",
    tokenId: "token4",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 4,
    activeContracts: 2,
    endedContracts: 2,
    views: 900,
    amountEarned: 400,
    averageContractLength: "2 months",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item5",
    name: "Artwork 5",
    collectionName: "Collection B",
    withExclusiveLicense: true,
    ownerName: "Owner B",
    ownerUserId: "user2",
    ownerLastActive: new Date("2023-01-05"),
    contractAddress: "0xLMN345",
    tokenId: "token5",
    tokenStandard: "ERC-1155",
    blockchain: "Polygon",
    contractProposals: 6,
    activeContracts: 3,
    endedContracts: 3,
    views: 1100,
    amountEarned: 600,
    averageContractLength: "1.5 months",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item6",
    name: "Artwork 6",
    collectionName: "Collection C",
    withExclusiveLicense: false,
    ownerName: "Owner C",
    ownerUserId: "user3",
    ownerLastActive: new Date("2023-01-06"),
    contractAddress: "0xOPQ678",
    tokenId: "token6",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 3,
    activeContracts: 1,
    endedContracts: 2,
    views: 950,
    amountEarned: 300,
    averageContractLength: "1 month",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item7",
    name: "Artwork 7",
    collectionName: "Collection A",
    withExclusiveLicense: true,
    ownerName: "Owner A",
    ownerUserId: "user1",
    ownerLastActive: new Date("2023-01-07"),
    contractAddress: "0xRST901",
    tokenId: "token7",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 5,
    activeContracts: 3,
    endedContracts: 2,
    views: 1050,
    amountEarned: 550,
    averageContractLength: "3 weeks",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item8",
    name: "Artwork 8",
    collectionName: "Collection B",
    withExclusiveLicense: false,
    ownerName: "Owner B",
    ownerUserId: "user2",
    ownerLastActive: new Date("2023-01-08"),
    contractAddress: "0xUVW234",
    tokenId: "token8",
    tokenStandard: "ERC-1155",
    blockchain: "Polygon",
    contractProposals: 4,
    activeContracts: 2,
    endedContracts: 2,
    views: 920,
    amountEarned: 450,
    averageContractLength: "2 months",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item9",
    name: "Artwork 9",
    collectionName: "Collection C",
    withExclusiveLicense: true,
    ownerName: "Owner C",
    ownerUserId: "user3",
    ownerLastActive: new Date("2023-01-09"),
    contractAddress: "0xXYZ567",
    tokenId: "token9",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 6,
    activeContracts: 3,
    endedContracts: 3,
    views: 1150,
    amountEarned: 650,
    averageContractLength: "1.5 months",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item10",
    name: "Artwork 10",
    collectionName: "Collection A",
    withExclusiveLicense: false,
    ownerName: "Owner A",
    ownerUserId: "user1",
    ownerLastActive: new Date("2023-01-10"),
    contractAddress: "0xBCD345",
    tokenId: "token10",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 2,
    activeContracts: 1,
    endedContracts: 1,
    views: 880,
    amountEarned: 400,
    averageContractLength: "1 month",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item11",
    name: "Artwork 11",
    collectionName: "Collection B",
    withExclusiveLicense: true,
    ownerName: "Owner B",
    ownerUserId: "user2",
    ownerLastActive: new Date("2023-01-11"),
    contractAddress: "0xCDE678",
    tokenId: "token11",
    tokenStandard: "ERC-1155",
    blockchain: "Polygon",
    contractProposals: 3,
    activeContracts: 2,
    endedContracts: 1,
    views: 850,
    amountEarned: 300,
    averageContractLength: "2 weeks",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item12",
    name: "Artwork 12",
    collectionName: "Collection C",
    withExclusiveLicense: false,
    ownerName: "Owner C",
    ownerUserId: "user3",
    ownerLastActive: new Date("2023-01-12"),
    contractAddress: "0xEFG789",
    tokenId: "token12",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 4,
    activeContracts: 2,
    endedContracts: 2,
    views: 1000,
    amountEarned: 450,
    averageContractLength: "3 weeks",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item13",
    name: "Artwork 13",
    collectionName: "Collection A",
    withExclusiveLicense: true,
    ownerName: "Owner A",
    ownerUserId: "user1",
    ownerLastActive: new Date("2023-01-13"),
    contractAddress: "0xFGH012",
    tokenId: "token13",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 7,
    activeContracts: 4,
    endedContracts: 3,
    views: 1100,
    amountEarned: 600,
    averageContractLength: "2 months",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item14",
    name: "Artwork 14",
    collectionName: "Collection B",
    withExclusiveLicense: false,
    ownerName: "Owner B",
    ownerUserId: "user2",
    ownerLastActive: new Date("2023-01-14"),
    contractAddress: "0xHIJ901",
    tokenId: "token14",
    tokenStandard: "ERC-1155",
    blockchain: "Polygon",
    contractProposals: 6,
    activeContracts: 3,
    endedContracts: 3,
    views: 950,
    amountEarned: 400,
    averageContractLength: "2 months",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item15",
    name: "Artwork 15",
    collectionName: "Collection C",
    withExclusiveLicense: true,
    ownerName: "Owner C",
    ownerUserId: "user3",
    ownerLastActive: new Date("2023-01-15"),
    contractAddress: "0xLMN234",
    tokenId: "token15",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 5,
    activeContracts: 2,
    endedContracts: 3,
    views: 1000,
    amountEarned: 550,
    averageContractLength: "1.5 months",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item16",
    name: "Artwork 16",
    collectionName: "Collection A",
    withExclusiveLicense: false,
    ownerName: "Owner A",
    ownerUserId: "user1",
    ownerLastActive: new Date("2023-01-16"),
    contractAddress: "0xOPQ567",
    tokenId: "token16",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 3,
    activeContracts: 1,
    endedContracts: 2,
    views: 900,
    amountEarned: 300,
    averageContractLength: "1 month",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item17",
    name: "Artwork 17",
    collectionName: "Collection B",
    withExclusiveLicense: true,
    ownerName: "Owner B",
    ownerUserId: "user2",
    ownerLastActive: new Date("2023-01-17"),
    contractAddress: "0xXYZ345",
    tokenId: "token17",
    tokenStandard: "ERC-1155",
    blockchain: "Polygon",
    contractProposals: 4,
    activeContracts: 2,
    endedContracts: 2,
    views: 1100,
    amountEarned: 600,
    averageContractLength: "2 weeks",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item18",
    name: "Artwork 18",
    collectionName: "Collection C",
    withExclusiveLicense: false,
    ownerName: "Owner C",
    ownerUserId: "user3",
    ownerLastActive: new Date("2023-01-18"),
    contractAddress: "0xABC678",
    tokenId: "token18",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 6,
    activeContracts: 3,
    endedContracts: 3,
    views: 950,
    amountEarned: 500,
    averageContractLength: "3 weeks",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item19",
    name: "Artwork 19",
    collectionName: "Collection A",
    withExclusiveLicense: true,
    ownerName: "Owner A",
    ownerUserId: "user1",
    ownerLastActive: new Date("2023-01-19"),
    contractAddress: "0xCDE901",
    tokenId: "token19",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 2,
    activeContracts: 1,
    endedContracts: 1,
    views: 880,
    amountEarned: 400,
    averageContractLength: "1 month",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item20",
    name: "Artwork 20",
    collectionName: "Collection B",
    withExclusiveLicense: false,
    ownerName: "Owner B",
    ownerUserId: "user2",
    ownerLastActive: new Date("2023-01-20"),
    contractAddress: "0xEFG789",
    tokenId: "token20",
    tokenStandard: "ERC-1155",
    blockchain: "Polygon",
    contractProposals: 3,
    activeContracts: 2,
    endedContracts: 1,
    views: 850,
    amountEarned: 300,
    averageContractLength: "2 weeks",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item21",
    name: "Artwork 21",
    collectionName: "Collection C",
    withExclusiveLicense: true,
    ownerName: "Owner C",
    ownerUserId: "user3",
    ownerLastActive: new Date("2023-01-21"),
    contractAddress: "0xFGH234",
    tokenId: "token21",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 4,
    activeContracts: 2,
    endedContracts: 2,
    views: 1000,
    amountEarned: 450,
    averageContractLength: "3 weeks",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item22",
    name: "Artwork 22",
    collectionName: "Collection A",
    withExclusiveLicense: false,
    ownerName: "Owner A",
    ownerUserId: "user1",
    ownerLastActive: new Date("2023-01-22"),
    contractAddress: "0xHIJ567",
    tokenId: "token22",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 7,
    activeContracts: 4,
    endedContracts: 3,
    views: 1050,
    amountEarned: 600,
    averageContractLength: "2 months",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item23",
    name: "Artwork 23",
    collectionName: "Collection B",
    withExclusiveLicense: true,
    ownerName: "Owner B",
    ownerUserId: "user2",
    ownerLastActive: new Date("2023-01-23"),
    contractAddress: "0xLMN901",
    tokenId: "token23",
    tokenStandard: "ERC-1155",
    blockchain: "Polygon",
    contractProposals: 5,
    activeContracts: 3,
    endedContracts: 2,
    views: 1200,
    amountEarned: 700,
    averageContractLength: "1.5 months",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item24",
    name: "Artwork 24",
    collectionName: "Collection C",
    withExclusiveLicense: false,
    ownerName: "Owner C",
    ownerUserId: "user3",
    ownerLastActive: new Date("2023-01-24"),
    contractAddress: "0xOPQ789",
    tokenId: "token24",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 4,
    activeContracts: 2,
    endedContracts: 2,
    views: 900,
    amountEarned: 400,
    averageContractLength: "1 month",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item25",
    name: "Artwork 25",
    collectionName: "Collection A",
    withExclusiveLicense: true,
    ownerName: "Owner A",
    ownerUserId: "user1",
    ownerLastActive: new Date("2023-01-25"),
    contractAddress: "0xRST345",
    tokenId: "token25",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 6,
    activeContracts: 3,
    endedContracts: 3,
    views: 1100,
    amountEarned: 650,
    averageContractLength: "2 weeks",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item26",
    name: "Artwork 26",
    collectionName: "Collection B",
    withExclusiveLicense: false,
    ownerName: "Owner B",
    ownerUserId: "user2",
    ownerLastActive: new Date("2023-01-26"),
    contractAddress: "0xUVW567",
    tokenId: "token26",
    tokenStandard: "ERC-1155",
    blockchain: "Polygon",
    contractProposals: 3,
    activeContracts: 2,
    endedContracts: 1,
    views: 950,
    amountEarned: 500,
    averageContractLength: "2 months",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item27",
    name: "Artwork 27",
    collectionName: "Collection C",
    withExclusiveLicense: true,
    ownerName: "Owner C",
    ownerUserId: "user3",
    ownerLastActive: new Date("2023-01-27"),
    contractAddress: "0xXYZ789",
    tokenId: "token27",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 5,
    activeContracts: 2,
    endedContracts: 3,
    views: 1000,
    amountEarned: 550,
    averageContractLength: "1.5 months",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item28",
    name: "Artwork 28",
    collectionName: "Collection A",
    withExclusiveLicense: false,
    ownerName: "Owner A",
    ownerUserId: "user1",
    ownerLastActive: new Date("2023-01-28"),
    contractAddress: "0xLMN678",
    tokenId: "token28",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 4,
    activeContracts: 1,
    endedContracts: 3,
    views: 1050,
    amountEarned: 600,
    averageContractLength: "1 month",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item29",
    name: "Artwork 29",
    collectionName: "Collection B",
    withExclusiveLicense: true,
    ownerName: "Owner B",
    ownerUserId: "user2",
    ownerLastActive: new Date("2023-01-29"),
    contractAddress: "0xABC901",
    tokenId: "token29",
    tokenStandard: "ERC-1155",
    blockchain: "Polygon",
    contractProposals: 6,
    activeContracts: 3,
    endedContracts: 3,
    views: 950,
    amountEarned: 500,
    averageContractLength: "3 weeks",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item30",
    name: "Artwork 30",
    collectionName: "Collection C",
    withExclusiveLicense: false,
    ownerName: "Owner C",
    ownerUserId: "user3",
    ownerLastActive: new Date("2023-01-30"),
    contractAddress: "0xCDE012",
    tokenId: "token30",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 2,
    activeContracts: 1,
    endedContracts: 1,
    views: 880,
    amountEarned: 400,
    averageContractLength: "2 weeks",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  }
]
