import { Catalog, CatalogMarketData, CatalogSalesData, CatalogTrendingData, NFT, Trait, User } from "./types";

export const user : User & { password: string; } = {
  id: "1",
  email: "user@email.com",
  password: "password",
  username: "mrknuckles",
  pfp: "/images/image_1.png",
  walletAddresses: [
    "1Lbcfr7sAHTD9CgdQo3HTMTkV8LK4ZnX71",
    "1Lbcfr7sAHTD9CgdQo3HTMTkV8LK4ZnX72",
    "1Lbcfr7sAHTD9CgdQo3HTMTkV8LK4ZnX73",
  ],
  joinedAt: new Date(),
  lastActiveAt: new Date(),
  responseTime: 77,
  responseRate: "Within the hour",
  website: "",
  twitter: "x.com/markiplier",
  instagram: "",
  discord: "",
  opensea: "",
  looksRare: "",
  catalogCount: 12,
  contractCount: 3,
};

const traits: Trait[] = [
  { traitType: "Background", value: "Gradient 2" },
  { traitType: "Head", value: "Purple" },
  { traitType: "Hair", value: "Brown Bushcut" },
  { traitType: "Face", value: "Straw" },
  { traitType: "Body", value: "Gradient 2" },
];

export const nfts: NFT[] = [
  {
    id: "item1",
    name: "Artwork 1",
    collectionName: "Collection A",
    withExclusiveLicense: true,
    ownerName: "Owner A",
    ownerUserId: "user1",
    ownerLastActive: new Date("2023-01-01"),
    contractAddress: "0xABC123",
    tokenId: "token1",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 5,
    activeContracts: 3,
    endedContracts: 2,
    views: 1000,
    amountEarned: 500,
    averageContractLength: "2 weeks",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item2",
    name: "Artwork 2",
    collectionName: "Collection B",
    withExclusiveLicense: false,
    ownerName: "Owner B",
    ownerUserId: "user2",
    ownerLastActive: new Date("2023-01-02"),
    contractAddress: "0xDEF456",
    tokenId: "token2",
    tokenStandard: "ERC-1155",
    blockchain: "Polygon",
    contractProposals: 3,
    activeContracts: 2,
    endedContracts: 1,
    views: 800,
    amountEarned: 300,
    averageContractLength: "1 month",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item3",
    name: "Artwork 3",
    collectionName: "Collection C",
    withExclusiveLicense: true,
    ownerName: "Owner C",
    ownerUserId: "user3",
    ownerLastActive: new Date("2023-01-03"),
    contractAddress: "0xGHI789",
    tokenId: "token3",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 7,
    activeContracts: 4,
    endedContracts: 3,
    views: 1200,
    amountEarned: 700,
    averageContractLength: "3 weeks",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item4",
    name: "Artwork 4",
    collectionName: "Collection A",
    withExclusiveLicense: false,
    ownerName: "Owner A",
    ownerUserId: "user1",
    ownerLastActive: new Date("2023-01-04"),
    contractAddress: "0xJKL012",
    tokenId: "token4",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 4,
    activeContracts: 2,
    endedContracts: 2,
    views: 900,
    amountEarned: 400,
    averageContractLength: "2 months",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item5",
    name: "Artwork 5",
    collectionName: "Collection B",
    withExclusiveLicense: true,
    ownerName: "Owner B",
    ownerUserId: "user2",
    ownerLastActive: new Date("2023-01-05"),
    contractAddress: "0xLMN345",
    tokenId: "token5",
    tokenStandard: "ERC-1155",
    blockchain: "Polygon",
    contractProposals: 6,
    activeContracts: 3,
    endedContracts: 3,
    views: 1100,
    amountEarned: 600,
    averageContractLength: "1.5 months",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item6",
    name: "Artwork 6",
    collectionName: "Collection C",
    withExclusiveLicense: false,
    ownerName: "Owner C",
    ownerUserId: "user3",
    ownerLastActive: new Date("2023-01-06"),
    contractAddress: "0xOPQ678",
    tokenId: "token6",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 3,
    activeContracts: 1,
    endedContracts: 2,
    views: 950,
    amountEarned: 300,
    averageContractLength: "1 month",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item7",
    name: "Artwork 7",
    collectionName: "Collection A",
    withExclusiveLicense: true,
    ownerName: "Owner A",
    ownerUserId: "user1",
    ownerLastActive: new Date("2023-01-07"),
    contractAddress: "0xRST901",
    tokenId: "token7",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 5,
    activeContracts: 3,
    endedContracts: 2,
    views: 1050,
    amountEarned: 550,
    averageContractLength: "3 weeks",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item8",
    name: "Artwork 8",
    collectionName: "Collection B",
    withExclusiveLicense: false,
    ownerName: "Owner B",
    ownerUserId: "user2",
    ownerLastActive: new Date("2023-01-08"),
    contractAddress: "0xUVW234",
    tokenId: "token8",
    tokenStandard: "ERC-1155",
    blockchain: "Polygon",
    contractProposals: 4,
    activeContracts: 2,
    endedContracts: 2,
    views: 920,
    amountEarned: 450,
    averageContractLength: "2 months",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item9",
    name: "Artwork 9",
    collectionName: "Collection C",
    withExclusiveLicense: true,
    ownerName: "Owner C",
    ownerUserId: "user3",
    ownerLastActive: new Date("2023-01-09"),
    contractAddress: "0xXYZ567",
    tokenId: "token9",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 6,
    activeContracts: 3,
    endedContracts: 3,
    views: 1150,
    amountEarned: 650,
    averageContractLength: "1.5 months",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item10",
    name: "Artwork 10",
    collectionName: "Collection A",
    withExclusiveLicense: false,
    ownerName: "Owner A",
    ownerUserId: "user1",
    ownerLastActive: new Date("2023-01-10"),
    contractAddress: "0xBCD345",
    tokenId: "token10",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 2,
    activeContracts: 1,
    endedContracts: 1,
    views: 880,
    amountEarned: 400,
    averageContractLength: "1 month",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item11",
    name: "Artwork 11",
    collectionName: "Collection B",
    withExclusiveLicense: true,
    ownerName: "Owner B",
    ownerUserId: "user2",
    ownerLastActive: new Date("2023-01-11"),
    contractAddress: "0xCDE678",
    tokenId: "token11",
    tokenStandard: "ERC-1155",
    blockchain: "Polygon",
    contractProposals: 3,
    activeContracts: 2,
    endedContracts: 1,
    views: 850,
    amountEarned: 300,
    averageContractLength: "2 weeks",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item12",
    name: "Artwork 12",
    collectionName: "Collection C",
    withExclusiveLicense: false,
    ownerName: "Owner C",
    ownerUserId: "user3",
    ownerLastActive: new Date("2023-01-12"),
    contractAddress: "0xEFG789",
    tokenId: "token12",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 4,
    activeContracts: 2,
    endedContracts: 2,
    views: 1000,
    amountEarned: 450,
    averageContractLength: "3 weeks",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item13",
    name: "Artwork 13",
    collectionName: "Collection A",
    withExclusiveLicense: true,
    ownerName: "Owner A",
    ownerUserId: "user1",
    ownerLastActive: new Date("2023-01-13"),
    contractAddress: "0xFGH012",
    tokenId: "token13",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 7,
    activeContracts: 4,
    endedContracts: 3,
    views: 1100,
    amountEarned: 600,
    averageContractLength: "2 months",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item14",
    name: "Artwork 14",
    collectionName: "Collection B",
    withExclusiveLicense: false,
    ownerName: "Owner B",
    ownerUserId: "user2",
    ownerLastActive: new Date("2023-01-14"),
    contractAddress: "0xHIJ901",
    tokenId: "token14",
    tokenStandard: "ERC-1155",
    blockchain: "Polygon",
    contractProposals: 6,
    activeContracts: 3,
    endedContracts: 3,
    views: 950,
    amountEarned: 400,
    averageContractLength: "2 months",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item15",
    name: "Artwork 15",
    collectionName: "Collection C",
    withExclusiveLicense: true,
    ownerName: "Owner C",
    ownerUserId: "user3",
    ownerLastActive: new Date("2023-01-15"),
    contractAddress: "0xLMN234",
    tokenId: "token15",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 5,
    activeContracts: 2,
    endedContracts: 3,
    views: 1000,
    amountEarned: 550,
    averageContractLength: "1.5 months",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item16",
    name: "Artwork 16",
    collectionName: "Collection A",
    withExclusiveLicense: false,
    ownerName: "Owner A",
    ownerUserId: "user1",
    ownerLastActive: new Date("2023-01-16"),
    contractAddress: "0xOPQ567",
    tokenId: "token16",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 3,
    activeContracts: 1,
    endedContracts: 2,
    views: 900,
    amountEarned: 300,
    averageContractLength: "1 month",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item17",
    name: "Artwork 17",
    collectionName: "Collection B",
    withExclusiveLicense: true,
    ownerName: "Owner B",
    ownerUserId: "user2",
    ownerLastActive: new Date("2023-01-17"),
    contractAddress: "0xXYZ345",
    tokenId: "token17",
    tokenStandard: "ERC-1155",
    blockchain: "Polygon",
    contractProposals: 4,
    activeContracts: 2,
    endedContracts: 2,
    views: 1100,
    amountEarned: 600,
    averageContractLength: "2 weeks",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item18",
    name: "Artwork 18",
    collectionName: "Collection C",
    withExclusiveLicense: false,
    ownerName: "Owner C",
    ownerUserId: "user3",
    ownerLastActive: new Date("2023-01-18"),
    contractAddress: "0xABC678",
    tokenId: "token18",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 6,
    activeContracts: 3,
    endedContracts: 3,
    views: 950,
    amountEarned: 500,
    averageContractLength: "3 weeks",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item19",
    name: "Artwork 19",
    collectionName: "Collection A",
    withExclusiveLicense: true,
    ownerName: "Owner A",
    ownerUserId: "user1",
    ownerLastActive: new Date("2023-01-19"),
    contractAddress: "0xCDE901",
    tokenId: "token19",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 2,
    activeContracts: 1,
    endedContracts: 1,
    views: 880,
    amountEarned: 400,
    averageContractLength: "1 month",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item20",
    name: "Artwork 20",
    collectionName: "Collection B",
    withExclusiveLicense: false,
    ownerName: "Owner B",
    ownerUserId: "user2",
    ownerLastActive: new Date("2023-01-20"),
    contractAddress: "0xEFG789",
    tokenId: "token20",
    tokenStandard: "ERC-1155",
    blockchain: "Polygon",
    contractProposals: 3,
    activeContracts: 2,
    endedContracts: 1,
    views: 850,
    amountEarned: 300,
    averageContractLength: "2 weeks",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item21",
    name: "Artwork 21",
    collectionName: "Collection C",
    withExclusiveLicense: true,
    ownerName: "Owner C",
    ownerUserId: "user3",
    ownerLastActive: new Date("2023-01-21"),
    contractAddress: "0xFGH234",
    tokenId: "token21",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 4,
    activeContracts: 2,
    endedContracts: 2,
    views: 1000,
    amountEarned: 450,
    averageContractLength: "3 weeks",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item22",
    name: "Artwork 22",
    collectionName: "Collection A",
    withExclusiveLicense: false,
    ownerName: "Owner A",
    ownerUserId: "user1",
    ownerLastActive: new Date("2023-01-22"),
    contractAddress: "0xHIJ567",
    tokenId: "token22",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 7,
    activeContracts: 4,
    endedContracts: 3,
    views: 1050,
    amountEarned: 600,
    averageContractLength: "2 months",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item23",
    name: "Artwork 23",
    collectionName: "Collection B",
    withExclusiveLicense: true,
    ownerName: "Owner B",
    ownerUserId: "user2",
    ownerLastActive: new Date("2023-01-23"),
    contractAddress: "0xLMN901",
    tokenId: "token23",
    tokenStandard: "ERC-1155",
    blockchain: "Polygon",
    contractProposals: 5,
    activeContracts: 3,
    endedContracts: 2,
    views: 1200,
    amountEarned: 700,
    averageContractLength: "1.5 months",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item24",
    name: "Artwork 24",
    collectionName: "Collection C",
    withExclusiveLicense: false,
    ownerName: "Owner C",
    ownerUserId: "user3",
    ownerLastActive: new Date("2023-01-24"),
    contractAddress: "0xOPQ789",
    tokenId: "token24",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 4,
    activeContracts: 2,
    endedContracts: 2,
    views: 900,
    amountEarned: 400,
    averageContractLength: "1 month",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item25",
    name: "Artwork 25",
    collectionName: "Collection A",
    withExclusiveLicense: true,
    ownerName: "Owner A",
    ownerUserId: "user1",
    ownerLastActive: new Date("2023-01-25"),
    contractAddress: "0xRST345",
    tokenId: "token25",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 6,
    activeContracts: 3,
    endedContracts: 3,
    views: 1100,
    amountEarned: 650,
    averageContractLength: "2 weeks",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item26",
    name: "Artwork 26",
    collectionName: "Collection B",
    withExclusiveLicense: false,
    ownerName: "Owner B",
    ownerUserId: "user2",
    ownerLastActive: new Date("2023-01-26"),
    contractAddress: "0xUVW567",
    tokenId: "token26",
    tokenStandard: "ERC-1155",
    blockchain: "Polygon",
    contractProposals: 3,
    activeContracts: 2,
    endedContracts: 1,
    views: 950,
    amountEarned: 500,
    averageContractLength: "2 months",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item27",
    name: "Artwork 27",
    collectionName: "Collection C",
    withExclusiveLicense: true,
    ownerName: "Owner C",
    ownerUserId: "user3",
    ownerLastActive: new Date("2023-01-27"),
    contractAddress: "0xXYZ789",
    tokenId: "token27",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 5,
    activeContracts: 2,
    endedContracts: 3,
    views: 1000,
    amountEarned: 550,
    averageContractLength: "1.5 months",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item28",
    name: "Artwork 28",
    collectionName: "Collection A",
    withExclusiveLicense: false,
    ownerName: "Owner A",
    ownerUserId: "user1",
    ownerLastActive: new Date("2023-01-28"),
    contractAddress: "0xLMN678",
    tokenId: "token28",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 4,
    activeContracts: 1,
    endedContracts: 3,
    views: 1050,
    amountEarned: 600,
    averageContractLength: "1 month",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item29",
    name: "Artwork 29",
    collectionName: "Collection B",
    withExclusiveLicense: true,
    ownerName: "Owner B",
    ownerUserId: "user2",
    ownerLastActive: new Date("2023-01-29"),
    contractAddress: "0xABC901",
    tokenId: "token29",
    tokenStandard: "ERC-1155",
    blockchain: "Polygon",
    contractProposals: 6,
    activeContracts: 3,
    endedContracts: 3,
    views: 950,
    amountEarned: 500,
    averageContractLength: "3 weeks",
    traits,
    private: false,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  },
  {
    id: "item30",
    name: "Artwork 30",
    collectionName: "Collection C",
    withExclusiveLicense: false,
    ownerName: "Owner C",
    ownerUserId: "user3",
    ownerLastActive: new Date("2023-01-30"),
    contractAddress: "0xCDE012",
    tokenId: "token30",
    tokenStandard: "ERC-721",
    blockchain: "Ethereum",
    contractProposals: 2,
    activeContracts: 1,
    endedContracts: 1,
    views: 880,
    amountEarned: 400,
    averageContractLength: "2 weeks",
    traits,
    private: true,
    image: "/images/image_4.png",
    price: 9.7,
    catalogCount: 12,
  }
]

export const users: User[] = [
  {
    id: "1",
    email: "user1@example.com",
    username: "user1",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x123"],
    joinedAt: new Date("2021-01-01"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 10,
    responseRate: "95%",
    website: "https://user1.com",
    twitter: "@user1",
    instagram: "user1_insta",
    discord: "user1#1234",
    opensea: "user1_opensea",
    looksRare: "user1_looksRare",
    catalogCount: 5,
    contractCount: 2
  },
  {
    id: "2",
    email: "user2@example.com",
    username: "user2",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x234"],
    joinedAt: new Date("2021-02-01"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 20,
    responseRate: "90%",
    website: "https://user2.com",
    twitter: "@user2",
    instagram: "user2_insta",
    discord: "user2#1234",
    opensea: "user2_opensea",
    looksRare: "user2_looksRare",
    catalogCount: 6,
    contractCount: 3
  },
  {
    id: "3",
    email: "user3@example.com",
    username: "user3",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x345"],
    joinedAt: new Date("2021-03-01"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 15,
    responseRate: "92%",
    website: "https://user3.com",
    twitter: "@user3",
    instagram: "user3_insta",
    discord: "user3#1234",
    opensea: "user3_opensea",
    looksRare: "user3_looksRare",
    catalogCount: 7,
    contractCount: 4
  },
  {
    id: "4",
    email: "user4@example.com",
    username: "user4",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x456"],
    joinedAt: new Date("2021-04-01"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 12,
    responseRate: "89%",
    website: "https://user4.com",
    twitter: "@user4",
    instagram: "user4_insta",
    discord: "user4#1234",
    opensea: "user4_opensea",
    looksRare: "user4_looksRare",
    catalogCount: 8,
    contractCount: 5
  },
  {
    id: "5",
    email: "user5@example.com",
    username: "user5",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x567"],
    joinedAt: new Date("2021-05-01"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 18,
    responseRate: "85%",
    website: "https://user5.com",
    twitter: "@user5",
    instagram: "user5_insta",
    discord: "user5#1234",
    opensea: "user5_opensea",
    looksRare: "user5_looksRare",
    catalogCount: 9,
    contractCount: 6
  },
  {
    id: "6",
    email: "user6@example.com",
    username: "user6",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x678"],
    joinedAt: new Date("2021-06-01"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 14,
    responseRate: "88%",
    website: "https://user6.com",
    twitter: "@user6",
    instagram: "user6_insta",
    discord: "user6#1234",
    opensea: "user6_opensea",
    looksRare: "user6_looksRare",
    catalogCount: 10,
    contractCount: 7
  },
  {
    id: "7",
    email: "user7@example.com",
    username: "user7",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x789"],
    joinedAt: new Date("2021-07-01"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 11,
    responseRate: "93%",
    website: "https://user7.com",
    twitter: "@user7",
    instagram: "user7_insta",
    discord: "user7#1234",
    opensea: "user7_opensea",
    looksRare: "user7_looksRare",
    catalogCount: 11,
    contractCount: 8
  },
  {
    id: "8",
    email: "user8@example.com",
    username: "user8",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x890"],
    joinedAt: new Date("2021-08-01"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 19,
    responseRate: "86%",
    website: "https://user8.com",
    twitter: "@user8",
    instagram: "user8_insta",
    discord: "user8#1234",
    opensea: "user8_opensea",
    looksRare: "user8_looksRare",
    catalogCount: 12,
    contractCount: 9
  },
  {
    id: "9",
    email: "user9@example.com",
    username: "user9",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x901"],
    joinedAt: new Date("2021-09-01"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 17,
    responseRate: "87%",
    website: "https://user9.com",
    twitter: "@user9",
    instagram: "user9_insta",
    discord: "user9#1234",
    opensea: "user9_opensea",
    looksRare: "user9_looksRare",
    catalogCount: 13,
    contractCount: 10
  },
  {
    id: "10",
    email: "user10@example.com",
    username: "user10",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x012"],
    joinedAt: new Date("2021-10-01"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 16,
    responseRate: "84%",
    website: "https://user10.com",
    twitter: "@user10",
    instagram: "user10_insta",
    discord: "user10#1234",
    opensea: "user10_opensea",
    looksRare: "user10_looksRare",
    catalogCount: 14,
    contractCount: 11
  },
  {
    id: "11",
    email: "user11@example.com",
    username: "user11",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x1234"],
    joinedAt: new Date("2021-11-01"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 13,
    responseRate: "91%",
    website: "https://user11.com",
    twitter: "@user11",
    instagram: "user11_insta",
    discord: "user11#1234",
    opensea: "user11_opensea",
    looksRare: "user11_looksRare",
    catalogCount: 15,
    contractCount: 12
  },
  {
    id: "12",
    email: "user12@example.com",
    username: "user12",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x2345"],
    joinedAt: new Date("2021-12-01"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 22,
    responseRate: "83%",
    website: "https://user12.com",
    twitter: "@user12",
    instagram: "user12_insta",
    discord: "user12#1234",
    opensea: "user12_opensea",
    looksRare: "user12_looksRare",
    catalogCount: 16,
    contractCount: 13
  },
  {
    id: "13",
    email: "user13@example.com",
    username: "user13",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x3456"],
    joinedAt: new Date("2021-11-15"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 23,
    responseRate: "94%",
    website: "https://user13.com",
    twitter: "@user13",
    instagram: "user13_insta",
    discord: "user13#1234",
    opensea: "user13_opensea",
    looksRare: "user13_looksRare",
    catalogCount: 17,
    contractCount: 14
  },
  {
    id: "14",
    email: "user14@example.com",
    username: "user14",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x4567"],
    joinedAt: new Date("2021-10-15"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 24,
    responseRate: "82%",
    website: "https://user14.com",
    twitter: "@user14",
    instagram: "user14_insta",
    discord: "user14#1234",
    opensea: "user14_opensea",
    looksRare: "user14_looksRare",
    catalogCount: 18,
    contractCount: 15
  },
  {
    id: "15",
    email: "user15@example.com",
    username: "user15",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x5678"],
    joinedAt: new Date("2021-09-15"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 25,
    responseRate: "81%",
    website: "https://user15.com",
    twitter: "@user15",
    instagram: "user15_insta",
    discord: "user15#1234",
    opensea: "user15_opensea",
    looksRare: "user15_looksRare",
    catalogCount: 19,
    contractCount: 16
  },
  {
    id: "16",
    email: "user16@example.com",
    username: "user16",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x6789"],
    joinedAt: new Date("2021-08-15"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 26,
    responseRate: "80%",
    website: "https://user16.com",
    twitter: "@user16",
    instagram: "user16_insta",
    discord: "user16#1234",
    opensea: "user16_opensea",
    looksRare: "user16_looksRare",
    catalogCount: 20,
    contractCount: 17
  },
  {
    id: "17",
    email: "user17@example.com",
    username: "user17",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x7890"],
    joinedAt: new Date("2021-07-15"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 27,
    responseRate: "79%",
    website: "https://user17.com",
    twitter: "@user17",
    instagram: "user17_insta",
    discord: "user17#1234",
    opensea: "user17_opensea",
    looksRare: "user17_looksRare",
    catalogCount: 21,
    contractCount: 18
  },
  {
    id: "18",
    email: "user18@example.com",
    username: "user18",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x8901"],
    joinedAt: new Date("2021-06-15"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 28,
    responseRate: "78%",
    website: "https://user18.com",
    twitter: "@user18",
    instagram: "user18_insta",
    discord: "user18#1234",
    opensea: "user18_opensea",
    looksRare: "user18_looksRare",
    catalogCount: 22,
    contractCount: 19
  },
  {
    id: "19",
    email: "user19@example.com",
    username: "user19",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x9012"],
    joinedAt: new Date("2021-05-15"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 29,
    responseRate: "77%",
    website: "https://user19.com",
    twitter: "@user19",
    instagram: "user19_insta",
    discord: "user19#1234",
    opensea: "user19_opensea",
    looksRare: "user19_looksRare",
    catalogCount: 23,
    contractCount: 20
  },
  {
    id: "20",
    email: "user20@example.com",
    username: "user20",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x0123"],
    joinedAt: new Date("2021-04-15"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 30,
    responseRate: "76%",
    website: "https://user20.com",
    twitter: "@user20",
    instagram: "user20_insta",
    discord: "user20#1234",
    opensea: "user20_opensea",
    looksRare: "user20_looksRare",
    catalogCount: 24,
    contractCount: 21
  },
  {
    id: "21",
    email: "user21@example.com",
    username: "user21",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x1234"],
    joinedAt: new Date("2021-03-15"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 31,
    responseRate: "75%",
    website: "https://user21.com",
    twitter: "@user21",
    instagram: "user21_insta",
    discord: "user21#1234",
    opensea: "user21_opensea",
    looksRare: "user21_looksRare",
    catalogCount: 25,
    contractCount: 22
  },
  {
    id: "22",
    email: "user22@example.com",
    username: "user22",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x2345"],
    joinedAt: new Date("2021-02-15"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 32,
    responseRate: "74%",
    website: "https://user22.com",
    twitter: "@user22",
    instagram: "user22_insta",
    discord: "user22#1234",
    opensea: "user22_opensea",
    looksRare: "user22_looksRare",
    catalogCount: 26,
    contractCount: 23
  },
  {
    id: "23",
    email: "user23@example.com",
    username: "user23",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x3456"],
    joinedAt: new Date("2021-01-15"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 33,
    responseRate: "73%",
    website: "https://user23.com",
    twitter: "@user23",
    instagram: "user23_insta",
    discord: "user23#1234",
    opensea: "user23_opensea",
    looksRare: "user23_looksRare",
    catalogCount: 27,
    contractCount: 24
  },
  {
    id: "24",
    email: "user24@example.com",
    username: "user24",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x4567"],
    joinedAt: new Date("2022-01-15"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 34,
    responseRate: "72%",
    website: "https://user24.com",
    twitter: "@user24",
    instagram: "user24_insta",
    discord: "user24#1234",
    opensea: "user24_opensea",
    looksRare: "user24_looksRare",
    catalogCount: 28,
    contractCount: 25
  },
  {
    id: "25",
    email: "user25@example.com",
    username: "user25",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x5678"],
    joinedAt: new Date("2022-02-15"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 35,
    responseRate: "71%",
    website: "https://user25.com",
    twitter: "@user25",
    instagram: "user25_insta",
    discord: "user25#1234",
    opensea: "user25_opensea",
    looksRare: "user25_looksRare",
    catalogCount: 29,
    contractCount: 26
  },
  {
    id: "26",
    email: "user26@example.com",
    username: "user26",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x6789"],
    joinedAt: new Date("2022-03-15"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 36,
    responseRate: "70%",
    website: "https://user26.com",
    twitter: "@user26",
    instagram: "user26_insta",
    discord: "user26#1234",
    opensea: "user26_opensea",
    looksRare: "user26_looksRare",
    catalogCount: 30,
    contractCount: 27
  },
  {
    id: "27",
    email: "user27@example.com",
    username: "user27",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x7890"],
    joinedAt: new Date("2022-04-15"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 37,
    responseRate: "69%",
    website: "https://user27.com",
    twitter: "@user27",
    instagram: "user27_insta",
    discord: "user27#1234",
    opensea: "user27_opensea",
    looksRare: "user27_looksRare",
    catalogCount: 31,
    contractCount: 28
  },
  {
    id: "28",
    email: "user28@example.com",
    username: "user28",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x8901"],
    joinedAt: new Date("2022-05-15"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 38,
    responseRate: "68%",
    website: "https://user28.com",
    twitter: "@user28",
    instagram: "user28_insta",
    discord: "user28#1234",
    opensea: "user28_opensea",
    looksRare: "user28_looksRare",
    catalogCount: 32,
    contractCount: 29
  },
  {
    id: "29",
    email: "user29@example.com",
    username: "user29",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x9012"],
    joinedAt: new Date("2022-06-15"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 39,
    responseRate: "67%",
    website: "https://user29.com",
    twitter: "@user29",
    instagram: "user29_insta",
    discord: "user29#1234",
    opensea: "user29_opensea",
    looksRare: "user29_looksRare",
    catalogCount: 33,
    contractCount: 30
  },
  {
    id: "30",
    email: "user30@example.com",
    username: "user30",
    pfp: "/images/image_1.png",
    walletAddresses: ["0x0123"],
    joinedAt: new Date("2022-07-15"),
    lastActiveAt: new Date("2021-01-01"),
    responseTime: 40,
    responseRate: "66%",
    website: "https://user30.com",
    twitter: "@user30",
    instagram: "user30_insta",
    discord: "user30#1234",
    opensea: "user30_opensea",
    looksRare: "user30_looksRare",
    catalogCount: 34,
    contractCount: 31
  }
];

export const catalogs: Catalog[] = [
  {
    id: "1",
    uid: "catalog-1",
    name: "Catalog 1",
    createdAt: new Date("2023-01-01"),
    coverImage: "/images/image_2.png",
    coverColor: "#FF5733",
    allowExclusiveLicense: true,
    creatorName: "Creator 1",
    creatorUserId: "creator1",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "2",
    uid: "catalog-2",
    name: "Catalog 2",
    createdAt: new Date("2023-01-02"),
    coverImage: "/images/image_2.png",
    coverColor: "#33FF57",
    allowExclusiveLicense: false,
    creatorName: "Creator 2",
    creatorUserId: "creator2",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "3",
    uid: "catalog-3",
    name: "Catalog 3",
    createdAt: new Date("2023-01-03"),
    coverImage: "/images/image_2.png",
    coverColor: "#5733FF",
    allowExclusiveLicense: true,
    creatorName: "Creator 3",
    creatorUserId: "creator3",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "4",
    uid: "catalog-4",
    name: "Catalog 4",
    createdAt: new Date("2023-01-04"),
    coverImage: "/images/image_2.png",
    coverColor: "#FF33A1",
    allowExclusiveLicense: false,
    creatorName: "Creator 4",
    creatorUserId: "creator4",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "5",
    uid: "catalog-5",
    name: "Catalog 5",
    createdAt: new Date("2023-01-05"),
    coverImage: "/images/image_2.png",
    coverColor: "#33A1FF",
    allowExclusiveLicense: true,
    creatorName: "Creator 5",
    creatorUserId: "creator5",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "6",
    uid: "catalog-6",
    name: "Catalog 6",
    createdAt: new Date("2023-01-06"),
    coverImage: "/images/image_2.png",
    coverColor: "#A1FF33",
    allowExclusiveLicense: false,
    creatorName: "Creator 6",
    creatorUserId: "creator6",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "7",
    uid: "catalog-7",
    name: "Catalog 7",
    createdAt: new Date("2023-01-07"),
    coverImage: "/images/image_2.png",
    coverColor: "#FF5733",
    allowExclusiveLicense: true,
    creatorName: "Creator 7",
    creatorUserId: "creator7",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "8",
    uid: "catalog-8",
    name: "Catalog 8",
    createdAt: new Date("2023-01-08"),
    coverImage: "/images/image_2.png",
    coverColor: "#33FF57",
    allowExclusiveLicense: false,
    creatorName: "Creator 8",
    creatorUserId: "creator8",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "9",
    uid: "catalog-9",
    name: "Catalog 9",
    createdAt: new Date("2023-01-09"),
    coverImage: "/images/image_2.png",
    coverColor: "#5733FF",
    allowExclusiveLicense: true,
    creatorName: "Creator 9",
    creatorUserId: "creator9",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "10",
    uid: "catalog-10",
    name: "Catalog 10",
    createdAt: new Date("2023-01-10"),
    coverImage: "/images/image_2.png",
    coverColor: "#FF33A1",
    allowExclusiveLicense: false,
    creatorName: "Creator 10",
    creatorUserId: "creator10",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "11",
    uid: "catalog-11",
    name: "Catalog 11",
    createdAt: new Date("2023-01-11"),
    coverImage: "/images/image_2.png",
    coverColor: "#33A1FF",
    allowExclusiveLicense: true,
    creatorName: "Creator 11",
    creatorUserId: "creator11",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "12",
    uid: "catalog-12",
    name: "Catalog 12",
    createdAt: new Date("2023-01-12"),
    coverImage: "/images/image_2.png",
    coverColor: "#A1FF33",
    allowExclusiveLicense: false,
    creatorName: "Creator 12",
    creatorUserId: "creator12",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "13",
    uid: "catalog-13",
    name: "Catalog 13",
    createdAt: new Date("2023-01-13"),
    coverImage: "/images/image_2.png",
    coverColor: "#FF5733",
    allowExclusiveLicense: true,
    creatorName: "Creator 13",
    creatorUserId: "creator13",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "14",
    uid: "catalog-14",
    name: "Catalog 14",
    createdAt: new Date("2023-01-14"),
    coverImage: "/images/image_2.png",
    coverColor: "#33FF57",
    allowExclusiveLicense: false,
    creatorName: "Creator 14",
    creatorUserId: "creator14",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "15",
    uid: "catalog-15",
    name: "Catalog 15",
    createdAt: new Date("2023-01-15"),
    coverImage: "/images/image_2.png",
    coverColor: "#5733FF",
    allowExclusiveLicense: true,
    creatorName: "Creator 15",
    creatorUserId: "creator15",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "16",
    uid: "catalog-16",
    name: "Catalog 16",
    createdAt: new Date("2023-01-16"),
    coverImage: "/images/image_2.png",
    coverColor: "#FF33A1",
    allowExclusiveLicense: false,
    creatorName: "Creator 16",
    creatorUserId: "creator16",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "17",
    uid: "catalog-17",
    name: "Catalog 17",
    createdAt: new Date("2023-01-17"),
    coverImage: "/images/image_2.png",
    coverColor: "#33A1FF",
    allowExclusiveLicense: true,
    creatorName: "Creator 17",
    creatorUserId: "creator17",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "18",
    uid: "catalog-18",
    name: "Catalog 18",
    createdAt: new Date("2023-01-18"),
    coverImage: "/images/image_2.png",
    coverColor: "#A1FF33",
    allowExclusiveLicense: false,
    creatorName: "Creator 18",
    creatorUserId: "creator18",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "19",
    uid: "catalog-19",
    name: "Catalog 19",
    createdAt: new Date("2023-01-19"),
    coverImage: "/images/image_2.png",
    coverColor: "#FF5733",
    allowExclusiveLicense: true,
    creatorName: "Creator 19",
    creatorUserId: "creator19",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "20",
    uid: "catalog-20",
    name: "Catalog 20",
    createdAt: new Date("2023-01-20"),
    coverImage: "/images/image_2.png",
    coverColor: "#33FF57",
    allowExclusiveLicense: false,
    creatorName: "Creator 20",
    creatorUserId: "creator20",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "21",
    uid: "catalog-21",
    name: "Catalog 21",
    createdAt: new Date("2023-01-21"),
    coverImage: "/images/image_2.png",
    coverColor: "#5733FF",
    allowExclusiveLicense: true,
    creatorName: "Creator 21",
    creatorUserId: "creator21",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "22",
    uid: "catalog-22",
    name: "Catalog 22",
    createdAt: new Date("2023-01-22"),
    coverImage: "/images/image_2.png",
    coverColor: "#FF33A1",
    allowExclusiveLicense: false,
    creatorName: "Creator 22",
    creatorUserId: "creator22",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "23",
    uid: "catalog-23",
    name: "Catalog 23",
    createdAt: new Date("2023-01-23"),
    coverImage: "/images/image_2.png",
    coverColor: "#33A1FF",
    allowExclusiveLicense: true,
    creatorName: "Creator 23",
    creatorUserId: "creator23",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "24",
    uid: "catalog-24",
    name: "Catalog 24",
    createdAt: new Date("2023-01-24"),
    coverImage: "/images/image_2.png",
    coverColor: "#A1FF33",
    allowExclusiveLicense: false,
    creatorName: "Creator 24",
    creatorUserId: "creator24",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "25",
    uid: "catalog-25",
    name: "Catalog 25",
    createdAt: new Date("2023-01-25"),
    coverImage: "/images/image_2.png",
    coverColor: "#FF5733",
    allowExclusiveLicense: true,
    creatorName: "Creator 25",
    creatorUserId: "creator25",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "26",
    uid: "catalog-26",
    name: "Catalog 26",
    createdAt: new Date("2023-01-26"),
    coverImage: "/images/image_2.png",
    coverColor: "#33FF57",
    allowExclusiveLicense: false,
    creatorName: "Creator 26",
    creatorUserId: "creator26",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "27",
    uid: "catalog-27",
    name: "Catalog 27",
    createdAt: new Date("2023-01-27"),
    coverImage: "/images/image_2.png",
    coverColor: "#5733FF",
    allowExclusiveLicense: true,
    creatorName: "Creator 27",
    creatorUserId: "creator27",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "28",
    uid: "catalog-28",
    name: "Catalog 28",
    createdAt: new Date("2023-01-28"),
    coverImage: "/images/image_2.png",
    coverColor: "#FF33A1",
    allowExclusiveLicense: false,
    creatorName: "Creator 28",
    creatorUserId: "creator28",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "29",
    uid: "catalog-29",
    name: "Catalog 29",
    createdAt: new Date("2023-01-29"),
    coverImage: "/images/image_2.png",
    coverColor: "#33A1FF",
    allowExclusiveLicense: true,
    creatorName: "Creator 29",
    creatorUserId: "creator29",
    nfts: nfts.slice(0, 15),
  },
  {
    id: "30",
    uid: "catalog-30",
    name: "Catalog 30",
    createdAt: new Date("2023-01-30"),
    coverImage: "/images/image_2.png",
    coverColor: "#A1FF33",
    allowExclusiveLicense: false,
    creatorName: "Creator 30",
    creatorUserId: "creator30",
    nfts: nfts.slice(0, 15),
  }
];

export const trendingCatalogs: CatalogTrendingData[] = [
  {
    id: "item1",
    rank: 1,
    price: 10.5,
    volume: 2000,
    volumeChange: 0.2,
    catalog: catalogs[0],
  },
  {
    id: "item2",
    rank: 2,
    price: 9.8,
    volume: 1800,
    volumeChange: -0.1,
    catalog: catalogs[1],
  },
  {
    id: "item3",
    rank: 3,
    price: 11.2,
    volume: 2200,
    volumeChange: 0.3,
    catalog: catalogs[2],
  },
  {
    id: "item4",
    rank: 4,
    price: 9.5,
    volume: 1900,
    volumeChange: -0.2,
    catalog: catalogs[3],
  },
  {
    id: "item5",
    rank: 5,
    price: 12.1,
    volume: 2400,
    volumeChange: 0.1,
    catalog: catalogs[4],
  },
  {
    id: "item6",
    rank: 6,
    price: 8.9,
    volume: 1700,
    volumeChange: -0.3,
    catalog: catalogs[5],
  },
  {
    id: "item7",
    rank: 7,
    price: 11.5,
    volume: 2100,
    volumeChange: 0.4,
    catalog: catalogs[6],
  },
  {
    id: "item8",
    rank: 8,
    price: 9.3,
    volume: 1850,
    volumeChange: -0.15,
    catalog: catalogs[7],
  },
  {
    id: "item9",
    rank: 9,
    price: 10.8,
    volume: 2300,
    volumeChange: 0.25,
    catalog: catalogs[8],
  },
  {
    id: "item10",
    rank: 10,
    price: 9.7,
    volume: 1950,
    volumeChange: -0.05,
    catalog: catalogs[9],
  }
];

export const marketCatalogs: CatalogMarketData[] = [
  {
    id: "item1",
    price: 10.5,
    priceChange: 0.2,
    catalog: catalogs[0],
  },
  {
    id: "item2",
    price: 9.8,
    priceChange: -0.1,
    catalog: catalogs[1],
  },
  {
    id: "item3",
    price: 11.2,
    priceChange: 0.3,
    catalog: catalogs[2],
  },
  {
    id: "item4",
    price: 9.5,
    priceChange: -0.2,
    catalog: catalogs[3],
  },
  {
    id: "item5",
    price: 12.1,
    priceChange: 0.1,
    catalog: catalogs[4],
  },
  {
    id: "item6",
    price: 8.9,
    priceChange: -0.3,
    catalog: catalogs[5],
  },
  {
    id: "item7",
    price: 11.5,
    priceChange: 0.4,
    catalog: catalogs[6],
  },
  {
    id: "item8",
    price: 9.3,
    priceChange: -0.15,
    catalog: catalogs[7],
  },
  {
    id: "item9",
    price: 10.8,
    priceChange: 0.25,
    catalog: catalogs[8],
  },
  {
    id: "item10",
    price: 9.7,
    priceChange: -0.05,
    catalog: catalogs[9],
  }
];

export const catalogSalesData: CatalogSalesData[] = [
  {
    id: "1",
    rank: 1,
    price: 100,
    quantity: 1,
    subtotal: 100,
    purchasedAt: new Date("2022-01-01"),
    catalog: catalogs[0],
    buyer: users[0],
  },
  {
    id: "2",
    rank: 2,
    price: 200,
    quantity: 2,
    subtotal: 400,
    purchasedAt: new Date("2022-02-01"),
    catalog: catalogs[1],
    buyer: users[1],
  },
  {
    id: "3",
    rank: 3,
    price: 150,
    quantity: 3,
    subtotal: 450,
    purchasedAt: new Date("2022-03-01"),
    catalog: catalogs[2],
    buyer: users[2],
  },
  {
    id: "4",
    rank: 4,
    price: 250,
    quantity: 4,
    subtotal: 1000,
    purchasedAt: new Date("2022-04-01"),
    catalog: catalogs[3],
    buyer: users[3],
  },
  {
    id: "5",
    rank: 5,
    price: 300,
    quantity: 5,
    subtotal: 1500,
    purchasedAt: new Date("2022-05-01"),
    catalog: catalogs[4],
    buyer: users[4],
  },
  {
    id: "6",
    rank: 6,
    price: 120,
    quantity: 6,
    subtotal: 720,
    purchasedAt: new Date("2022-06-01"),
    catalog: catalogs[5],
    buyer: users[5],
  },
  {
    id: "7",
    rank: 7,
    price: 180,
    quantity: 7,
    subtotal: 1260,
    purchasedAt: new Date("2022-07-01"),
    catalog: catalogs[6],
    buyer: users[6],
  },
  {
    id: "8",
    rank: 8,
    price: 220,
    quantity: 8,
    subtotal: 1760,
    purchasedAt: new Date("2022-08-01"),
    catalog: catalogs[7],
    buyer: users[7],
  },
  {
    id: "9",
    rank: 9,
    price: 270,
    quantity: 9,
    subtotal: 2430,
    purchasedAt: new Date("2022-09-01"),
    catalog: catalogs[8],
    buyer: users[8],
  },
  {
    id: "10",
    rank: 10,
    price: 320,
    quantity: 10,
    subtotal: 3200,
    purchasedAt: new Date("2022-10-01"),
    catalog: catalogs[9],
    buyer: users[9],
  },
  {
    id: "11",
    rank: 11,
    price: 140,
    quantity: 11,
    subtotal: 1540,
    purchasedAt: new Date("2022-11-01"),
    catalog: catalogs[10],
    buyer: users[10],
  },
  {
    id: "12",
    rank: 12,
    price: 160,
    quantity: 12,
    subtotal: 1920,
    purchasedAt: new Date("2022-12-01"),
    catalog: catalogs[11],
    buyer: users[11],
  },
  {
    id: "13",
    rank: 13,
    price: 130,
    quantity: 13,
    subtotal: 1690,
    purchasedAt: new Date("2023-01-01"),
    catalog: catalogs[12],
    buyer: users[12],
  },
  {
    id: "14",
    rank: 14,
    price: 210,
    quantity: 14,
    subtotal: 2940,
    purchasedAt: new Date("2023-02-01"),
    catalog: catalogs[13],
    buyer: users[13],
  },
  {
    id: "15",
    rank: 15,
    price: 240,
    quantity: 15,
    subtotal: 3600,
    purchasedAt: new Date("2023-03-01"),
    catalog: catalogs[14],
    buyer: users[14],
  },
  {
    id: "16",
    rank: 16,
    price: 190,
    quantity: 16,
    subtotal: 3040,
    purchasedAt: new Date("2023-04-01"),
    catalog: catalogs[15],
    buyer: users[15],
  },
  {
    id: "17",
    rank: 17,
    price: 280,
    quantity: 17,
    subtotal: 4760,
    purchasedAt: new Date("2023-05-01"),
    catalog: catalogs[16],
    buyer: users[16],
  },
  {
    id: "18",
    rank: 18,
    price: 310,
    quantity: 18,
    subtotal: 5580,
    purchasedAt: new Date("2023-06-01"),
    catalog: catalogs[17],
    buyer: users[17],
  },
  {
    id: "19",
    rank: 19,
    price: 330,
    quantity: 19,
    subtotal: 6270,
    purchasedAt: new Date("2023-07-01"),
    catalog: catalogs[18],
    buyer: users[18],
  },
  {
    id: "20",
    rank: 20,
    price: 350,
    quantity: 20,
    subtotal: 7000,
    purchasedAt: new Date("2023-08-01"),
    catalog: catalogs[19],
    buyer: users[19],
  },
  {
    id: "21",
    rank: 21,
    price: 170,
    quantity: 21,
    subtotal: 3570,
    purchasedAt: new Date("2023-09-01"),
    catalog: catalogs[20],
    buyer: users[20],
  },
  {
    id: "22",
    rank: 22,
    price: 260,
    quantity: 22,
    subtotal: 5720,
    purchasedAt: new Date("2023-10-01"),
    catalog: catalogs[21],
    buyer: users[21],
  },
  {
    id: "23",
    rank: 23,
    price: 290,
    quantity: 23,
    subtotal: 6670,
    purchasedAt: new Date("2023-11-01"),
    catalog: catalogs[22],
    buyer: users[22],
  },
  {
    id: "24",
    rank: 24,
    price: 200,
    quantity: 24,
    subtotal: 4800,
    purchasedAt: new Date("2023-12-01"),
    catalog: catalogs[23],
    buyer: users[23],
  },
  {
    id: "25",
    rank: 25,
    price: 270,
    quantity: 25,
    subtotal: 6750,
    purchasedAt: new Date("2024-01-01"),
    catalog: catalogs[24],
    buyer: users[24],
  },
  {
    id: "26",
    rank: 26,
    price: 230,
    quantity: 26,
    subtotal: 5980,
    purchasedAt: new Date("2024-02-01"),
    catalog: catalogs[25],
    buyer: users[25],
  },
  {
    id: "27",
    rank: 27,
    price: 300,
    quantity: 27,
    subtotal: 8100,
    purchasedAt: new Date("2024-03-01"),
    catalog: catalogs[26],
    buyer: users[26],
  },
  {
    id: "28",
    rank: 28,
    price: 350,
    quantity: 28,
    subtotal: 9800,
    purchasedAt: new Date("2024-04-01"),
    catalog: catalogs[27],
    buyer: users[27],
  },
  {
    id: "29",
    rank: 29,
    price: 220,
    quantity: 29,
    subtotal: 6380,
    purchasedAt: new Date("2024-05-01"),
    catalog: catalogs[28],
    buyer: users[28],
  },
  {
    id: "30",
    rank: 30,
    price: 340,
    quantity: 30,
    subtotal: 10200,
    purchasedAt: new Date("2024-06-01"),
    catalog: catalogs[29],
    buyer: users[29],
  }
];
